### ISSUE TITLE
为何下载下拉的文件没有xcworkspace

### ISSUE THREAD

**Issue by tqhy8899** [srxboys/RXExtenstion#3]
用了pod的   但是打开是无法运行的   没有看到xcworkspace文件

**Comment by srxboys** [comment]
你需要 `pod install`  ， 安装后 就有 `xcworkspace `了。

有的人只是看代码不会运行，下载的包也不会太大。

如果想运行，就 `pod install`  安装下第三方库，如果你用过pod 安装过`某库`，会从本地走，不会占用网速，下载也快、省时。

so 。 我没有把 `pod install` 后的文件，上传到 GitHub上

**Comment by tqhy8899** [comment]
OK  那我直接pod下来
